import React, { useEffect, useMemo, useState } from 'react'

const fmtNum=(v,d=2)=>v==null||!Number.isFinite(Number(v))?'—':Number(v).toFixed(d)
const fmtPct=v=>v==null||!Number.isFinite(Number(v))?'—':(Number(v)>=0?'+':'')+Number(v).toFixed(2)+'%'
const fmtCr=v=>v==null||!Number.isFinite(Number(v))?'—':(Number(v)>=0?'+':'')+Number(v).toFixed(0)+' Cr'
const toneForPct=v=>v==null||!Number.isFinite(Number(v))||Math.abs(Number(v))<.15?'neutral':Number(v)>0?'positive':'negative'

function CueCard({item}){return <div className="mi-cue"><div className="mi-cue-name">{item.name}</div><strong>{item.name==='USD/INR'?'₹':''}{fmtNum(item.last,item.name==='GIFT Nifty'?0:2)}{item.name==='US 10Y'?'%':''}</strong><span className={'mi-change '+toneForPct(item.pct)}>{fmtPct(item.pct)}</span></div>}
function QuickMetric({label,value,sub,tone='neutral',accent=''}){return <div className={'mi-quick-card '+accent}><span>{label}</span><strong className={tone}>{value}</strong>{sub&&<small>{sub}</small>}</div>}
function SectorImpact({item}){const score=Number(item.score)||0;return <div className="mi-sector"><div className="mi-sector-top"><strong>{item.sector}</strong><span className={score>10?'positive':score<-10?'negative':'neutral'}>{score>0?'+':''}{fmtNum(score,0)}</span></div><div className="mi-sector-bar"><span className={score>10?'positive-bar':score<-10?'negative-bar':'neutral-bar'} style={{width:Math.min(100,Math.abs(score))+'%'}}/></div><div className="mi-sector-bottom"><span>{item.direction}</span><small>{item.reason}</small></div>{Number(item.ai_adjustment)!==0&&<div className="mi-ai-adjustment">AI news adjustment {item.ai_adjustment>0?'+':''}{fmtNum(item.ai_adjustment,0)}</div>}</div>}
function NewsCard({item}){const impact=item.impact||'medium';return <article className={'mi-news-card '+impact}><div className="mi-news-meta"><span className={'impact-badge '+impact}>{impact}</span><span>{item.source||'Google News'}</span></div><h4>{item.headline}</h4><p>{item.summary||'Fresh market headline captured from the configured news feed.'}</p>{item.sectors?.length&&<div className="mi-tags">{item.sectors.map(x=><span key={x}>{x}</span>)}</div>}</article>}
function GlobalCoverage({items}){const expected=['Nasdaq','Dow','S&P 500','Nikkei','Hang Seng','FTSE 100','DAX','CAC 40','Brent','WTI','USD/INR'];const byName=new Map((items||[]).map(x=>[x.name,x]));return <div className="mi-global-coverage">{expected.map(name=>{const item=byName.get(name);return <div className={'mi-global-card '+(item?'available':'missing')} key={name}><div className="mi-global-name">{name}</div><strong>{item?(name==='USD/INR'?'₹':'')+fmtNum(item.last,2):'Not available'}</strong><span className={item?toneForPct(item.pct):'neutral'}>{item?fmtPct(item.pct):'Not published by Upstox'}</span></div>})}</div>}
function QuickNav(){return <nav className="mi-quick-nav">{[['global','Global'],['india','India'],['drivers','Drivers'],['sectors','Sectors'],['news','News'],['scenarios','Scenarios']].map(([id,label])=><a key={id} href={'#mi-'+id}>{label}</a>)}</nav>}

function MarketIntelligence({apiUrl}){
 const [report,setReport]=useState(null),[history,setHistory]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState('')
 const load=async()=>{try{const [latest,hist]=await Promise.all([fetch(apiUrl('/api/market-intelligence/latest')),fetch(apiUrl('/api/market-intelligence/history?limit=8'))]);if(latest.ok)setReport(await latest.json());if(hist.ok)setHistory(await hist.json())}catch(e){setError('Unable to load market intelligence: '+e.message)}}
 useEffect(()=>{load()},[])
 const generate=async()=>{setLoading(true);setError('');try{const response=await fetch(apiUrl('/api/market-intelligence/generate'),{method:'POST'});const body=await response.json();if(!response.ok)throw new Error(body.detail||'Report generation failed');setReport(body);await load()}catch(e){setError(e.message)}finally{setLoading(false)}}
 const global=report?.global_cues||[],india=report?.india_snapshot||[]
 const sectors=useMemo(()=>[...(report?.sector_impacts||[])].sort((a,b)=>Math.abs(Number(b.score)||0)-Math.abs(Number(a.score)||0)),[report])
 const positiveSectors=sectors.filter(x=>Number(x.score)>10).slice(0,5),negativeSectors=sectors.filter(x=>Number(x.score)<-10).slice(0,5)
 const fii=india.find(x=>x.name==='FII'),dii=india.find(x=>x.name==='DII'),breadth=india.find(x=>x.name==='Breadth'),nifty=india.find(x=>x.name==='NIFTY 50'||x.name==='Nifty 50'),vix=india.find(x=>x.name==='India VIX'),gift=global.find(x=>x.name==='GIFT Nifty'),brent=global.find(x=>x.name==='Brent')
 const primaryIndia=useMemo(()=>india.filter(x=>!['FII','DII','Breadth'].includes(x.name)),[india])
 if(!report)return <main className="mi-page"><section className="mi-header"><div><div className="section-kicker">MARKET INTELLIGENCE</div><h1>India pre-market report</h1><p>Fresh global cues, India data, grounded news and sector read-through in one view.</p></div><button className="button-primary" onClick={generate} disabled={loading}>{loading?'Generating…':'↻ Generate fresh report'}</button></section>{error&&<div className="banner error-banner">{error}</div>}<div className="mi-empty"><strong>No report generated yet</strong><span>Generate a report to fetch current market data and news.</span></div></main>
 return <main className="mi-page">
  <section className="mi-header"><div><div className="section-kicker">MARKET INTELLIGENCE</div><h1>India pre-market report</h1><p>Global cues, India data, flows, sector signals and news — optimized for a quick morning scan.</p></div><div className="mi-header-actions"><span className="mi-updated">Updated {new Date(report.generated_at).toLocaleString()}</span><button className="button-primary" onClick={generate} disabled={loading}>{loading?'Gathering markets + news…':'↻ Generate fresh report'}</button></div></section>
  {error&&<div className="banner error-banner">{error}</div>}
  <QuickNav/>
  <section className="mi-at-glance"><div className="mi-glance-heading"><div><span className="mi-label">AT A GLANCE</span><h2>What matters right now</h2></div><span>Key signals from the latest report</span></div><div className="mi-quick-grid">
   <QuickMetric label="NIFTY 50" value={fmtNum(nifty?.last,0)} sub={fmtPct(nifty?.pct)} tone={toneForPct(nifty?.pct)} accent="primary"/>
   <QuickMetric label="GIFT NIFTY" value={fmtNum(gift?.last,0)} sub={fmtPct(gift?.pct)} tone={toneForPct(gift?.pct)}/>
   <QuickMetric label="FII FLOW" value={fmtCr(fii?.last)} sub="Latest reported session" tone={Number(fii?.last)<0?'negative':'positive'}/>
   <QuickMetric label="DII FLOW" value={fmtCr(dii?.last)} sub="Latest reported session" tone={Number(dii?.last)>=0?'positive':'negative'}/>
   <QuickMetric label="INDIA VIX" value={fmtNum(vix?.last,2)} sub={fmtPct(vix?.pct)} tone={toneForPct(vix?.pct)}/>
   <QuickMetric label="BRENT" value={brent?'$'+fmtNum(brent.last,2):'—'} sub={fmtPct(brent?.pct)} tone={toneForPct(brent?.pct)}/>
   <QuickMetric label="BREADTH" value={breadth?breadth.advances+'/'+breadth.declines:'—'} sub={breadth?breadth.advances+' advances · '+breadth.declines+' declines':''} tone={breadth&&breadth.advances>=breadth.declines?'positive':'negative'}/>
   <QuickMetric label="PRESSURE" value={(report.market_pressure>0?'+':'')+fmtNum(report.market_pressure,0)} sub={report.market_mood} tone={report.market_pressure>=10?'positive':report.market_pressure<=-10?'negative':'neutral'} accent="pressure"/>
  </div></section>
  <section className="mi-mood"><div className="mi-mood-main"><span className="mi-label">MARKET MOOD</span><h2>{report.market_mood}</h2><p>{report.summary}</p></div><div className="mi-score"><span>Market pressure</span><strong className={report.market_pressure>=0?'positive':'negative'}>{report.market_pressure>0?'+':''}{fmtNum(report.market_pressure,0)}</strong><small>-100 bearish · 0 neutral · +100 positive</small></div><div className="mi-score"><span>Confidence</span><strong>{fmtNum(report.confidence,0)}%</strong><small>Data coverage + news agreement</small></div></section>
  <section className="mi-section" id="mi-global"><div className="mi-section-head"><div><h2>Global overnight cues</h2><span>US, Europe, Asia, commodities and currency</span></div><span className="mi-source">UPSTOX</span></div><div className="mi-cue-grid">{global.map(x=><CueCard item={x} key={x.name}/>)}</div><div className="mi-subsection-title">Coverage</div><GlobalCoverage items={[...global,...india.filter(x=>x.name==='USD/INR')]}/></section>
  <section className="mi-section" id="mi-india"><div className="mi-section-head"><div><h2>India market</h2><span>Indices, breadth and institutional flows</span></div><span className="mi-source">NSE + UPSTOX</span></div><div className="mi-india-grid">{primaryIndia.map(x=><div className="mi-big-stat" key={x.name}><span>{x.name}</span><strong>{fmtNum(x.last,x.name.includes('VIX')?2:0)}</strong><small className={toneForPct(x.pct)}>{fmtPct(x.pct)}</small></div>)}<div className="mi-big-stat institutional"><span>FII</span><strong>{fmtCr(fii?.last)}</strong><small>Latest session</small></div><div className="mi-big-stat institutional"><span>DII</span><strong>{fmtCr(dii?.last)}</strong><small>Latest session</small></div><div className="mi-big-stat institutional"><span>Breadth</span><strong>{breadth?breadth.advances+':'+breadth.declines:'—'}</strong><small>{breadth?breadth.advances+' adv · '+breadth.declines+' dec · '+(breadth.unchanged||0)+' unchanged':''}</small></div></div></section>
  <section className="mi-section" id="mi-drivers"><div className="mi-section-head"><div><h2>Why is the market moving?</h2><span>Largest drivers from the current market inputs</span></div><span className="mi-source">RULES + GEMINI</span></div><div className="mi-driver-list">{(report.drivers||[]).map((d,i)=><div className="mi-driver" key={i}><span className={'driver-symbol '+d.direction}>{d.direction==='positive'?'↑':d.direction==='negative'?'↓':'→'}</span><div><strong>{d.title}</strong><p>{d.explanation}</p></div><b>{d.impact>0?'+':''}{fmtNum(d.impact,0)}</b></div>)}</div></section>
  <section className="mi-section" id="mi-sectors"><div className="mi-section-head"><div><h2>Sector radar</h2><span>Potential support and pressure based on current inputs</span></div></div><div className="mi-sector-columns"><div><div className="mi-column-title positive">Support</div>{positiveSectors.length?positiveSectors.map(x=><SectorImpact key={x.sector} item={x}/>):<div className="mi-muted">No strong positive signal.</div>}</div><div><div className="mi-column-title negative">Pressure</div>{negativeSectors.length?negativeSectors.map(x=><SectorImpact key={x.sector} item={x}/>):<div className="mi-muted">No strong negative signal.</div>}</div></div>{sectors.length>10&&<details className="mi-more"><summary>Show all sectors</summary><div className="mi-all-sectors">{sectors.map(x=><SectorImpact key={x.sector} item={x}/>)}</div></details>}</section>
  <section className="mi-section" id="mi-news"><div className="mi-section-head"><div><h2>News intelligence</h2><span>Fresh headlines and available sector context</span></div><span className="mi-source">GOOGLE NEWS RSS</span></div>{report.news_items?.length?<div className="mi-news-grid">{report.news_items.map((x,i)=><NewsCard item={x} key={i}/>)}</div>:<div className="mi-muted">No fresh news returned.</div>}{report.sources?.length&&<div className="mi-sources"><strong>Sources</strong>{report.sources.slice(0,10).map((x,i)=><a href={x.url} target="_blank" rel="noreferrer" key={i}>{x.title||x.url}</a>)}</div>}</section>
  <section className="mi-section" id="mi-scenarios"><div className="mi-section-head"><div><h2>Scenarios</h2><span>Conditional paths based on observable triggers</span></div><span className="mi-source">AI OUTLOOK</span></div><div className="mi-scenario-grid">{(report.scenarios||[]).map((x,i)=><div className={'mi-scenario scenario-'+i} key={x.name||i}><div className="mi-scenario-name">{x.name}</div><div className="mi-scenario-label">Trigger</div><strong>{x.trigger||x.observable_trigger||'No trigger returned.'}</strong><div className="mi-scenario-label">India read-through</div><p>{x.read_through||x.india_market_readthrough||'No read-through returned.'}</p></div>)}</div></section>
  <section className="mi-bottom-grid"><div className="mi-section"><div className="mi-section-head"><div><h2>Today's outlook</h2><span>Conditional read-through</span></div></div><p className="mi-outlook">{report.outlook}</p><div className="mi-subheading">Watch</div><div className="mi-watch">{(report.watchlist||[]).map(x=><span key={x}>{x}</span>)}</div></div><div className="mi-section"><div className="mi-section-head"><div><h2>Events & data quality</h2><span>Items that can change the read</span></div></div><div className="mi-event-list">{(report.events||[]).map((x,i)=><div key={i}>• {x}</div>)}{!(report.events||[]).length&&<div className="mi-muted">No additional events returned.</div>}</div>{report.data_quality?.length?<div className="mi-quality"><strong>Data notes</strong>{report.data_quality.map((x,i)=><div key={i}>• {x}</div>)}</div>:<div className="mi-quality good">No recorded data-quality warnings.</div>}</div></section>
  <section className="mi-section mi-history"><div className="mi-section-head"><div><h2>Previous reports</h2><span>Manual generations saved for comparison</span></div></div><div className="mi-history-list">{history.map(x=><button key={x.id} onClick={()=>setReport(x)} className={x.id===report.id?'active':''}><strong>{new Date(x.generated_at).toLocaleDateString()}</strong><span>{x.market_mood}</span><b>{x.market_pressure>0?'+':''}{fmtNum(x.market_pressure,0)}</b></button>)}</div></section>
 </main>
}
export default MarketIntelligence
